name: parkcheck_owner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_functions: ^6.0.4
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_stripe: ^12.1.1
  url_launcher: ^6.2.5
  intl: ^0.20.2 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
